[package]
name = 'astgrepr'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['staticlib']
name = 'astgrepr'

[dependencies]
ast-grep-core = "*"
ast-grep-config = "*"
ast-grep-language = "*"
extendr-api = { version = "*", features = ["serde"] }
once_cell = "1.19.0"
anyhow = "1.0.75"
tree-sitter-r = "0.19.5"
serde = "1.0.197"
